# Collaborative filltering based

In [93]:
import pandas as pd
import numpy as np

anime = pd.read_csv("Anime Data/anime.csv")

In [94]:
anime.head(20)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855
7,820,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",OVA,110,9.11,80679
8,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109
10,4181,Clannad: After Story,"Drama, Fantasy, Romance, Slice of Life, Supern...",TV,24,9.06,456749
11,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733
12,918,Gintama,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376
13,2904,Code Geass: Hangyaku no Lelouch R2,"Action, Drama, Mecha, Military, Sci-Fi, Super ...",TV,25,8.98,572888
14,28891,Haikyuu!! Second Season,"Comedy, Drama, School, Shounen, Sports",TV,25,8.93,179342
15,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
16,23273,Shigatsu wa Kimi no Uso,"Drama, Music, Romance, School, Shounen",TV,22,8.92,416397
17,24701,Mushishi Zoku Shou 2nd Season,"Adventure, Fantasy, Historical, Mystery, Seine...",TV,10,8.88,75894
18,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193
19,1575,Code Geass: Hangyaku no Lelouch,"Action, Mecha, Military, School, Sci-Fi, Super...",TV,25,8.83,715151

In [95]:
filtered_df = anime[anime['name'] == 'Haikyuu!! Second Season']['anime_id']

In [96]:
animeID =  anime[anime['name'] == 'Haikyuu!! Second Season']['anime_id']

In [97]:
filtered_df.iloc[0]

28891

In [98]:
animeID.iloc[0]

28891

In [99]:
import re

def clean_name(name):
    
    return re.sub("[^a-zA-Z0-9 ]", "", name)

In [100]:
anime["cleaned_name"] = anime["name"].apply(clean_name)

In [101]:
anime.head(20)

,anime_id,name,genre,type,episodes,rating,members,cleaned_name
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,Kimi no Na wa
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,Fullmetal Alchemist Brotherhood
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,Gintama
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,SteinsGate
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,Gintama039
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351,Haikyuu Karasuno Koukou VS Shiratorizawa Gakue...
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855,Hunter x Hunter 2011
7,820,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",OVA,110,9.11,80679,Ginga Eiyuu Densetsu
8,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534,Gintama Movie Kanketsuhen Yorozuya yo Eien Nare
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109,Gintama039 Enchousen
10,4181,Clannad: After Story,"Drama, Fantasy, Romance, Slice of Life, Supern...",TV,24,9.06,456749,Clannad After Story
11,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733,Koe no Katachi
12,918,Gintama,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376,Gintama
13,2904,Code Geass: Hangyaku no Lelouch R2,"Action, Drama, Mecha, Military, Sci-Fi, Super ...",TV,25,8.98,572888,Code Geass Hangyaku no Lelouch R2
14,28891,Haikyuu!! Second Season,"Comedy, Drama, School, Shounen, Sports",TV,25,8.93,179342,Haikyuu Second Season
15,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254,Sen to Chihiro no Kamikakushi
16,23273,Shigatsu wa Kimi no Uso,"Drama, Music, Romance, School, Shounen",TV,22,8.92,416397,Shigatsu wa Kimi no Uso
17,24701,Mushishi Zoku Shou 2nd Season,"Adventure, Fantasy, Historical, Mystery, Seine...",TV,10,8.88,75894,Mushishi Zoku Shou 2nd Season
18,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193,Ookami Kodomo no Ame to Yuki
19,1575,Code Geass: Hangyaku no Lelouch,"Action, Mecha, Military, School, Sci-Fi, Super...",TV,25,8.83,715151,Code Geass Hangyaku no Lelouch

In [102]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Count vectorization
vectoriser = TfidfVectorizer(ngram_range = (1,2)) # we have a vector/ matrix

tfidf = vectoriser.fit_transform(anime["cleaned_name"])

In [103]:
#Finding the similar animes using cosine similarity

from sklearn.metrics.pairwise import cosine_similarity

def search(name):
    name = clean_name(name)
    query_vector = vectoriser.transform([name])
    similarity = cosine_similarity(query_vector, tfidf).flatten()
    
    indices = np.argsort(similarity)[-5:]
    
#     indices = np.argpartition(similarity, -5)[-5:] # finds the five most similar items to our search term
    
    results = anime.iloc[indices][::-1]
    
    return results

In [104]:
search("Naruto: Shippuuden")

,anime_id,name,genre,type,episodes,rating,members,cleaned_name
615,1735,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,Unknown,7.94,533578,Naruto Shippuuden
1827,2472,Naruto: Shippuuden Movie 1,"Action, Adventure, Comedy, Fantasy, Shounen",Movie,1,7.43,108170,Naruto Shippuuden Movie 1
1828,4437,Naruto: Shippuuden Movie 2 - Kizuna,"Action, Martial Arts, Shounen, Supernatural",Movie,1,7.43,97818,Naruto Shippuuden Movie 2 Kizuna
1237,10589,Naruto: Shippuuden Movie 5 - Blood Prison,"Action, Adventure, Martial Arts, Mystery, Shou...",Movie,1,7.62,75660,Naruto Shippuuden Movie 5 Blood Prison
841,20,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297,Naruto

In [105]:
# Ratings Data 

ratings = pd.read_csv("Anime Data/rating.csv")

In [106]:
ratings.head(20)

    user_id  anime_id  rating
0         1        20      -1
1         1        24      -1
2         1        79      -1
3         1       226      -1
4         1       241      -1
5         1       355      -1
6         1       356      -1
7         1       442      -1
8         1       487      -1
9         1       846      -1
10        1       936      -1
11        1      1546      -1
12        1      1692      -1
13        1      1836      -1
14        1      2001      -1
15        1      2025      -1
16        1      2144      -1
17        1      2787      -1
18        1      2993      -1
19        1      3455      -1

In [107]:
# finding the similar users 

# users who like haikyu
similar_users = ratings[(ratings["anime_id"] == 28891) & (ratings["rating"] > 8)]["user_id"].unique()
similar_users

array([    3,     5,    17, ..., 73289, 73378, 73463])

In [108]:
# other anime that similiar users like
# vahi users jinko meri jaise pasand hai and unko baki sab kya pasand hai 

similar_user_recommendations = ratings[(ratings["user_id"].isin(similar_users))& (ratings["rating"] > 8)]["anime_id"]
similar_user_recommendations

158          170
159          199
160          225
165          813
173         1535
           ...
7808941    15613
7808942    16498
7808943    16894
7808944    18507
7808945    28891
Name: anime_id, Length: 202032, dtype: int64

In [109]:
similar_user_recommendations.value_counts() # this shows that Haikyuu(28891) have maximum count as I like haikyu

28891    2311
20583    1828
5114     1400
30276    1393
16498    1385
         ...
28683       1
16119       1
30641       1
2799        1
31919       1
Name: anime_id, Length: 4554, dtype: int64

In [110]:
similar_user_recommendations = similar_user_recommendations.value_counts()/len(similar_users)

In [111]:
# we only need more the 20% of the anime for the recommendations 
similar_user_recommendations = similar_user_recommendations[similar_user_recommendations > 0.20]

In [112]:
similar_user_recommendations

28891    1.000000
20583    0.791000
5114     0.605798
30276    0.602769
16498    0.599308
           ...
14813    0.203808
28121    0.203808
20       0.202510
3588     0.202077
18897    0.201644
Name: anime_id, Length: 72, dtype: float64

In [113]:
# checking all the other users who have rated the movie and in our recommendation data frame
'''
The condition being checked is whether each value in the "anime_id" column of the "ratings"
DataFrame is present in the index of another DataFrame called "similar_user_recommendations".
'''

# this checks if any one who has rated the anime is in our similar_user_recommendations dataframe and also given 
# rating more than 8
all_users = ratings[ratings["anime_id"].isin(similar_user_recommendations.index) & (ratings['rating'] > 8)]
all_users

         user_id  anime_id  rating
83             1     11757      10
153            2     11771      10
159            3       199      10
173            3      1535      10
183            3      5114      10
...          ...       ...     ...
7813665    73515      5114      10
7813697    73515      9253       9
7813704    73515     10087       9
7813714    73515     11741       9
7813716    73515     11757       9

[502038 rows x 3 columns]

In [114]:
# calculate the percentage of these users 
all_users_recommendations = all_users['anime_id'].value_counts() / len(all_users["user_id"].unique())

In [115]:
all_users_recommendations

1535     0.379798
5114     0.298292
1575     0.281622
16498    0.266827
2904     0.262879
           ...
24415    0.041367
31964    0.040488
28891    0.038331
32282    0.025195
32935    0.013651
Name: anime_id, Length: 72, dtype: float64

In [116]:
# viewing both the similar and all user recommendations
rec_percentages = pd.concat([similar_user_recommendations, all_users_recommendations], axis=1)
rec_percentages.columns = ["similar", "all"]
rec_percentages

        similar       all
28891  1.000000  0.038331
20583  0.791000  0.061619
5114   0.605798  0.298292
30276  0.602769  0.132510
16498  0.599308  0.266827
...         ...       ...
14813  0.203808  0.063692
28121  0.203808  0.046857
20     0.202510  0.129789
3588   0.202077  0.122342
18897  0.201644  0.054321

[72 rows x 2 columns]

In [117]:
rec_percentages["score"] = rec_percentages["similar"] / rec_percentages["all"]
rec_percentages = rec_percentages.sort_values("score", ascending=False)
rec_percentages

        similar       all      score
28891  1.000000  0.038331  26.088273
32935  0.294678  0.013651  21.587016
20583  0.791000  0.061619  12.836975
24415  0.392038  0.041367   9.477135
32282  0.217655  0.025195   8.638842
...         ...       ...        ...
431    0.217655  0.152845   1.424026
853    0.206404  0.146625   1.407704
164    0.204241  0.147371   1.385894
1535   0.525314  0.379798   1.383141
121    0.208135  0.183695   1.133044

[72 rows x 3 columns]

In [118]:
rec_percentage = rec_percentages.merge(anime, left_index = True, right_on = "anime_id")["name"]

In [119]:
def anime_recommendation(animeID):
    
    # find users similar to us 
    similar_users = ratings[(ratings["anime_id"] == animeID) & (ratings["rating"] > 8)]["user_id"].unique()
    similar_user_recs = ratings[(ratings["user_id"].isin(similar_users)) & (ratings["rating"] > 8)]["anime_id"]
    
    #percentatge of the user who are similar to us and like the movie
    similar_user_recs = similar_user_recs.value_counts() / len(similar_users)
    similar_user_recs = similar_user_recs[similar_user_recs > .20]
    
    # all of the users and there recommendations
    all_users = ratings[ratings["anime_id"].isin(similar_user_recs.index) & (ratings['rating'] > 8)]
    all_users_recs = all_users['anime_id'].value_counts() / len(all_users["user_id"].unique())
    
    # find the percentage
    rec_percentages = pd.concat([similar_user_recs, all_users_recs], axis=1)
    rec_percentages.columns = ["similar", "all"]
    
    rec_percentages["score"] = rec_percentages["similar"] / rec_percentages["all"]
    
    rec_percentages = rec_percentages.sort_values("score", ascending=False)
    return rec_percentages.head(10).merge(anime, left_index=True, right_on="anime_id")["cleaned_name"]

In [120]:
anime_recommendation(32)

130     Neon Genesis Evangelion The End of Evangelion
1538        Neon Genesis Evangelion Death amp Rebirth
294                   Evangelion 10 You Are Not Alone
211                           Neon Genesis Evangelion
90                  Evangelion 20 You Can Not Advance
191                                Ghost in the Shell
358                                             Akira
456                                              FLCL
156                                    NHK ni Youkoso
22                                       Cowboy Bebop
Name: cleaned_name, dtype: object

In [121]:
import ipywidgets as widgets
from IPython.display import display

anime_name_input = widgets.Text(
    description='Anime name:',
    disabled=False
)
recommendation_list = widgets.Output()

def on_type(data):
    with recommendation_list:
        recommendation_list.clear_output()
        name = data["new"]
        if len(name) > 3:
            results = search(name)
            animeID = results.iloc[0]["anime_id"]
            display(anime_recommendation(animeID))

anime_name_input.observe(on_type, names='value')

display(anime_name_input, recommendation_list)

Text(value='', description='Anime name:')

Output()

In [122]:
import ipywidgets as widgets
from IPython.display import display

anime_name_input = widgets.Text(
    description='Anime name:',
    disabled=False
)
recommendation_list = widgets.Output()

def on_type(data):
    with recommendation_list:
        recommendation_list.clear_output()
        name = data["new"]
        if len(name) > 3:
            results = search(name)
            animeID = results.iloc[0]["anime_id"]
            display(anime_recommendation(animeID))

anime_name_input.observe(on_type, names='value')

display(anime_name_input, recommendation_list)

Text(value='', description='Anime name:')

Output()

In [41]:
import pickle

In [30]:
pickle.dump(anime, open('anime.pkl', 'wb'))

In [42]:
pickle.dump(rec_percentage, open('rec_percent.pkl', 'wb'))

In [43]:
pickle.dump(ratings, open('ratings.pkl', 'wb'))